fn_calcRegion <- function(CSMF, ENV_REGION = NULL, KEY_REGION, KEY_CODLIST = NULL, AGGAGE = FALSE, CODALL = NULL){
  
  #' @title Calculate CSMFs for global regions
  # 
  #' @description Converts CSMFs to deaths, back calculates denominator, aggregates deaths and population counts by region, recalculates CSMFs and all-cause mortality rate.
  #
  #' @param CSMF Data frame with CSMFs that have been processed by squeezing functions, CSMFs that were not squeezed (GOODVR), all-cause crisis-free and crisis-included deaths and rates.
  #' @param ENV_REGION Regional envelopes provided by IGME. If not provided, regional envelopes generated by aggregating national.
  #' @param KEY_REGION Data frame with countries and different regional classifications.
  #' @param KEY_CODLIST Data frame with CODs that are modeled or reported for a given age group
  #' @param AGGAGE Boolean for whether being calculated for an aggregate age group
  #' @param CODALL Vector of all CODs for 5-19, for use in calculations of aggregate age groups
  #' @return Data frame with regional CSMFs, all-cause crisis-included deaths and rates.
  
  # Merge regions onto national estimates
  dat <- merge(CSMF, KEY_REGION, by = "iso3")
  
  # Create world region
  datWorld <- dat
  datWorld$Region <- "World"
  dat <- rbind(dat, datWorld)
  
  if(!AGGAGE){
    # Vector with causes of death for 5 year age groups
    v_cod <- unique(subset(KEY_CODLIST, ModeledOrReported == "Reported")$COD)
  }
  if(AGGAGE){
    # Vector with all causes of death
    v_cod <- CODALL[CODALL %in% names(dat)]
  }
  
  # Convert CSMFs to deaths
  dat[, paste(v_cod)] <- dat[, paste(v_cod)] * dat$Deaths2
  
  # Back calculate denominator from deaths and mortality rate
  dat$Px <- dat$Deaths2/dat$Rate2
  
  # Aggregate deaths and denominators for countries for each region
  dat_list <- lapply(split(dat, dat$Region), function(x) {
    tmp <- aggregate(x[, c("Deaths1", "Deaths2", "Px", v_cod)], 
                     by = list(year = x$year), 
                     sum, na.rm = TRUE)
    tmp$Region <- unique(x$Region)
    tmp
  })
  dat <- do.call(rbind, dat_list)
  
  # Re-calculate CSMFs
  dat[, paste(v_cod)] <- dat[, paste(v_cod)] / dat$Deaths2
  
  # Re-calculate mortality rate
  dat$Rate1 <- dat$Deaths1/dat$Px
  dat$Rate2 <- dat$Deaths2/dat$Px
  
  # Remove denominator
  dat <- dat[, names(dat) != "Px"]

  # If regional envelopes have been provided by IGME, use them for 10-14 and 15-19.
  # Do not do for 5-9, due to epidemic measles being added on top of envelope.
  if(ageSexSuffix %in% c("10to14y", "15to19yF", "15to19yM") & !is.null(ENV_REGION)){
    
    # Delete manually calculated all-cause deaths and rates columns
    dat <- dat[,c("Region", "year", v_cod)]
    
    # Merge on IGME all-cause regional deaths and rates
    dat <- merge(dat, ENV_REGION, by = c("Region", "year"))
    
  }
  
  # Order columns
  dat <- dat[, c("Region", "year", "Deaths1", "Rate1", "Deaths2", "Rate2", v_cod)]
  
  # Tidy up
  dat <- dat[order(dat$Region, dat$year), ]
  dat$Region <- as.character(dat$Region)
  rownames(dat) <- NULL
  
  return(dat)
  
}
